{% extends "admin/layout.swig" %}

{% block body %}
	<h1 class="page-header">欢迎回来，主人<small>一切如常喵。</small></h1>
	<div class="well">
		<h3>统计信息<small>东西好多啊喵....</small></h3>
		<div class="row-fluid">
			<div class="span4">
				<h4>全站用户数</h4>
				<h2>233</h2>
				<h5>今日新增：20</h5>
			</div>
			<div class="span4">
				<h4>全站文章数</h4>
				<h2>30</h2>
				<h5>今日新增：5</h5>
			</div>
			<div class="span4">
				<h4>全站评论数</h4>
				<h2>60</h2>
				<h5>今日新增：33</h5>
			</div>
		</div>
	</div>



{% endblock %}