<div class="navbar navbar-inverse">
	<div class="navbar-inner">
		<ul class="nav">
			<a href="#" class="brand">管理面板</a>
		</ul>
		<ul class="nav pull-right">
			<li class="dropdown">
				<a href="#" class="dropdown-toggle" data-toggle="dropdown">
					{{ display_name }}
					<b class="caret"></b>
				</a>
				<ul class="dropdown-menu">
					<li><a href="#">退出</a></li>
				</ul>
			</li>
		</ul>
	</div>
</div>